# Gurobi Solver Parameters
# Common solver settings
Feasib_Tol: 1.0e-05           # Constraint (primal) feasibility tolerances.
Optimal_Tol: 1e-5             # Dual feasibility tolerances.
TimeLimit: 110000             # Limits total time solver.
Pre_Solve: 1                  # Controls presolve level.
Method: 2                  # Algorithm used to solve continuous models (including MIP root relaxation).

#Gurobi-specific solver settings
MIPGap: 1e-3                  # Relative (p.u. of optimal) mixed integer optimality tolerance for MIP problems (ignored otherwise).
BarConvTol: 1.0e-08           # Barrier convergence tolerance (determines when barrier terminates).
NumericFocus: 0               # Numerical precision emphasis.
Crossover: 0                # Barrier crossver strategy.
PreDual: 0                    # Decides whether presolve should pass the primal or dual linear programming problem to the LP optimization algorithm.
AggFill: 10                   # Allowed fill during presolve aggregation.
