@doc raw"""
	write_power(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)

Function for writing the different values of power generated by the different technologies in operation.
"""
function write_status_of_charge_utes(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)

    gen = inputs["RESOURCES"]

    T = inputs["T"]     # Number of time steps (hours)
    Z = inputs["Z"]     # Number of zones
    UTES = inputs["UTES"]     # Number of UTES resources
    
    weight = inputs["omega"]
    scale_factor = setup["ParameterScale"] == 1 ? ModelScalingFactor : 1

    utes_resources = inputs["RESOURCE_NAMES"][UTES]
    df_output = DataFrame(Resource = 
		[utes_resources .*"_utes_soc_MJ";
         utes_resources .*"_utes_mass_flow_kg_per_s";])

	status_of_charge = value.(EP[:vSOC_RTES])[UTES,:]
    mass_flow = value.(EP[:vMassFlow_RTES])[UTES,:]

    if setup["ParameterScale"] == 1
        status_of_charge *= ModelScalingFactor
        mass_flow *= ModelScalingFactor
    end

    output = [Array(status_of_charge);
              Array(mass_flow);]

	final_output = permutedims(DataFrame(hcat(Array(df_output), output), :auto))
    CSV.write(joinpath(path,"UTES_hourly_status_of_charge.csv"), final_output, writeheader = false)

end