@doc raw"""
	write_power(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)

Function for writing the different values of power generated by the different technologies in operation.
"""
function write_energy_consumption_utes(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)

    gen = inputs["RESOURCES"]

    T = inputs["T"]     # Number of time steps (hours)
    Z = inputs["Z"]     # Number of zones
    UTES = inputs["UTES"]     # Number of UTES resources
    
    weight = inputs["omega"]
    scale_factor = setup["ParameterScale"] == 1 ? ModelScalingFactor : 1

    utes_resources = inputs["RESOURCE_NAMES"][UTES]
    df_output = DataFrame(Resource = 
		[utes_resources .*"_dry_cooler_consumption_mw";
         utes_resources .*"_chiller_consumption_power_mw";
         utes_resources .*"_thermal_storage_consumption_power_mw";
         utes_resources .*"_CRM_contribution_mw";
         utes_resources .*"_coverage_chiller";],)

	power_dry_cooler = value.(EP[:eElec_DC])[UTES,:]
    power_chiller = value.(EP[:eElec_Chiller])[UTES,:]
    if setup["withUTES"] == 1
        power_thermal_storage = value.(EP[:eElec_RTES])[UTES,:]
        crm = value.(EP[:vCRM_RTES])[UTES,:]
    else
        power_thermal_storage = zeros(length(UTES), T)
        crm = zeros(length(UTES), T)
    end

    coverage_chiller = value.(EP[:eCoverage_Chiller])[UTES,:]

    if setup["ParameterScale"] == 1
        power_chiller *= ModelScalingFactor
        power_dry_cooler *= ModelScalingFactor
        power_thermal_storage *= ModelScalingFactor
    end

    output = [Array(power_dry_cooler);
              Array(power_chiller);
              Array(power_thermal_storage);
              Array(crm);
              Array(coverage_chiller);]

	final_output = permutedims(DataFrame(hcat(Array(df_output), output), :auto))
    CSV.write(joinpath(path,"UTES_hourly_consumption.csv"), final_output, writeheader = false)

end
