NumStages: 3 # Number of model investment planning stages
StageLengths: [10,10,10] # Length of each model stage (years)
DiscountRate: 0.045  # General discount rate (planner's time value of money)
ConvergenceTolerance: 0.01 # Relative optimality gap used for convergence
Myopic: 1 # If using multi-stage GenX, 1 = myopic, 0 = dual dynamic programming
WriteIntermittentOutputs: 0 # If 1, write intermediate outputs to disk