IterativelyAddPeriods: 1
ExtremePeriods: 1
UseExtremePeriods: 1
MinPeriods: 8
MaxPeriods: 11
DemandWeight: 1
ClusterFuelPrices: 1
nReps: 100
MultiStageConcatenate: 0
Threshold: 0.05
TimestepsPerRepPeriod: 168
IterateMethod: "cluster"
ScalingMethod: "S"
ClusterMethod: "kmeans"
WeightTotal: 8760
