#default_location: default/path/to/data
# system
#system_location: path/to/data
demand_name: "Demand_data.csv"
fuel_name: "Fuels_data.csv.gz"

# policies
#policies_location: /path/to/data
#co2_name: file_or_table_name
#minimum_capacity_name: file_or_table_name

# resources


# policy assignments