capacity: "Capacity_test.csv"
capacity_factor: "capacityfactor.parquet"
charge: "charge.csv"
charging_cost: "ChargingCost.csv"
co2_prices: "CO2_prices_and_penalties.csv"
commit: "commit"
costs: "costs"
curtail: "curtail"
emissions_plant: "emissions_plant"



