[type.csv]
extend-glob = ["*.csv"]
check-file = false
[type.svg]
extend-glob = ["*.svg"]
check-file = false
[type.cff]
extend-glob = ["*.cff"]
check-file = false
[type.hunspellWhitelist]
extend-glob = ["hunspell_whitelist"]
check-file = false