@doc raw"""
	write_power(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)

Function for writing the different values of power generated by the different technologies in operation.
"""
function write_cascade_pumping_reversible_power(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)
    HYDRO_PUMPS = inputs["HYDRO_PUMPS"]
    gen = inputs["RESOURCES"]   # Resources (objects)
    pump_units = gen[HYDRO_PUMPS]
    resources = inputs["RESOURCE_NAMES"][HYDRO_PUMPS]    # Resource names
    zones = zone_id.(pump_units)

    H = length(HYDRO_PUMPS)     # Number of resources (generators, storage, DR, and DERs)
    T = inputs["T"]     # Number of time steps (hours)
    
    weight = inputs["omega"]
    scale_factor = setup["ParameterScale"] == 1 ? ModelScalingFactor : 1

    # Power injected by each resource in each time step
    pumping = value.(EP[:vP_PUMP_DISCHARGE]).data    # .data: DenseAxisArray to Vector
    pumping *= scale_factor

    df = DataFrame(Resource = resources,
        Zone = zones,
        AnnualSum = zeros(H))
    df.AnnualSum .= pumping * weight

    write_temporal_data(df, pumping, path, setup, "hydro_pumping_reversible_power")
    return df
end
