@doc raw"""
	write_power(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)

Function for writing the different values of power generated by the different technologies in operation.
"""
function write_cascade_hydro(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)
    HYDRO_RES = inputs["HYDRO_RES"]
    gen = inputs["RESOURCES"]   # Resources (objects)
    hydro_units = gen[HYDRO_RES]
    resources = inputs["RESOURCE_NAMES"][HYDRO_RES]    # Resource names
    zones = zone_id.(hydro_units)

    H = length(HYDRO_RES)     # Number of resources (generators, storage, DR, and DERs)
    T = inputs["T"]     # Number of time steps (hours)
    
    weight = inputs["omega"]
    scale_factor = setup["ParameterScale"] == 1 ? ModelScalingFactor : 1

    # Power injected by each resource in each time step
    discharge = value.(EP[:vDISCHARGE]).data    # .data: DenseAxisArray to Vector
    #discharge *= scale_factor

    df = DataFrame(Resource = resources,
        Zone = zones,
        AnnualSum = zeros(H))
    df.AnnualSum .= discharge * weight

    write_temporal_data(df, discharge, path, setup, "hydro_discharge")
    return df
end
