name: Changelog Enforcer
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces update of changelog file on every pull request
  Changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: 'CHANGELOG.md'
          skipLabels: 'Skip-Changelog, skip changelog'
          token: ${{ secrets.GITHUB_TOKEN }}
          missingUpdateErrorMessage: >
            No update to CHANGELOG.md found! Please add an entry describing 
            your change and include the pull request tag. Note that we use 
            the keepachangelog format (https://keepachangelog.com). If your 
            change doesn’t require a changelog entry, please add the 
            'Skip-Changelog' or 'skip changelog' label to the pull request.
