name: Typo Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y wget hunspell hunspell-en-us
      - name: Install typos
        id: typo-install
        run: |
          pwd
          mkdir ~/typos
          cd ~/typos
          wget -O typos.tar.gz https://github.com/crate-ci/typos/releases/download/v1.29.5/typos-v1.29.5-x86_64-unknown-linux-musl.tar.gz
          tar xavf typos.tar.gz
      - name: Run typo check
        id: typo-check
        run: |
          set -e
          touch tmpfile
          ~/typos/typos --words --config=docs/typos.toml | sort -u | hunspell -l -p docs/hunspell_whitelist - > tmpfile
          if [ -s tmpfile ]; then
            echo "*Typos found:*"
            echo "    (Can fix, modify docs/hunspell_whitelist, or add file type exception to docs/typos.toml)"
            cat tmpfile
            exit 1
          fi
